[bird] drum kit 구현 완료
JNU-econovation/javascript-study-30days pull request #12
Opened 2019-03-10 12:11 UTC by forbid403

맥북이 고장나서 조금 늦었습니당 ㅠ 리뷰 부탁드려요~

2019-03-10 13:35 UTC, corykim0829 requested changes
잘하셨습니다~ 조금만 더 수정하면 될 것 같아요! 함수를 더 분리해보고 keyClicked는 뭔가 인자가 필요없는 함수명 같아서 조금만 바꾸면 의미 전달이 잘될 것 같아요! + trello 가입해주세요~ (공지사항 참고)

2019-03-10 13:35 UTC, corykim0829 commented on 01 - JavaScript Drum Kit/drum.js
> +function playSound(e) {
animation 부분을 다른 함수로 분리해보면 좋을 것 같아요

2019-03-10 13:35 UTC, corykim0829 commented on 01 - JavaScript Drum Kit/drum.js
> +    window.addEventListener('keydown', playSound);
addEventListener는 한번만 추가해도 계속해서 이벤트를 받기 때문에 한번만 받아도 될 것 같습니다!
onclick으로도 구현하시려고 한거 맞나요? 다른 방법으로 도전해보세요!

2019-03-13 06:41 UTC, GiPyoo reviewed
잘하셔습니다. 아래 리뷰 반영 해주시면 머지 해드리겠습니다. 👍 👍

2019-03-13 06:41 UTC, GiPyoo commented on 01 - JavaScript Drum Kit/drum.js
> +function playSound(e) {
파라미터에 의미가 있었으면 좋겠습니다.  클린코드에 대해 읽어보다가 이런 이벤트 파라미터 조차도 의미가 있어보이는게 좋을 것 같다고 생각하게 되었습니다.

2019-03-13 06:41 UTC, GiPyoo commented on 01 - JavaScript Drum Kit/drum.js
> +    this.classList.remove('playing');
이 곳의 this는 무엇을 가리킬까요? 답글로 달아 주세요 😄

2019-03-13 11:19 UTC, Parkhyunseo commented on 01 - JavaScript Drum Kit/drum.js
> +function addAnimation(key) {
key를 이 함수에서만 사용 할거라면, 여기서 key변수를 정의하는게 좋을 것 같네요!

2019-03-15 14:59 UTC, corykim0829 commented on 01 - JavaScript Drum Kit/drum.js
> +function playSound(clicked) {
clicked라고 하면 형용사 이기 때문에 인자명 의미가 정확하지 못하네요! 명사로 하시는게 좋을 것 같아요

2019-03-15 15:03 UTC, corykim0829 reviewed
인자들만 조금 수정하며 끝날 것 같아요! 수고 많으셨습니다. :) 👍

2019-03-15 15:03 UTC, corykim0829 commented on 01 - JavaScript Drum Kit/drum.js
> +function playSound(clicked) {
EventListener이기 때문에 event를 인자로 받기 때문에 event가 좋을 것 같아요!

2019-03-15 15:03 UTC, corykim0829 commented on 01 - JavaScript Drum Kit/drum.js
> +function removeTransition(played) {
여기도 인자를 살짝 수정하시면 좋을 것 같아요!

2019-03-16 13:56 UTC, closed without merging