[Judy] Day3 complete
JNU-econovation/javascript-study-30days pull request #20
Opened 2019-03-18 12:55 UTC by mywnajsldkf

Day3 리뷰부탁드립니다!!

2019-03-18 16:28 UTC, corykim0829 requested changes
잘하셨습니다~ 피드백 반영해주시고 배운 내용 잘 정리해서 과제방에 올려주세요

2019-03-18 16:28 UTC, corykim0829 commented on 03 - CSS Variables/START.js
> + const picSize = this.dataset.sizing || '';
picSize라고 하면 실질적인 size value 값을 나타내는 것 같아요! 수정 부탁드려요

2019-03-18 16:28 UTC, corykim0829 commented on 03 - CSS Variables/index-START.html
> +  <script src="START.js">
이렇게 한다면 잘 실행 되나요? 몰라서 여쭤보는거에요~

2019-03-19 06:17 UTC, mywnajsldkf commented on 03 - CSS Variables/index-START.html
> +  <script src="START.js">
네! 그렇습니다!!!

2019-03-19 06:18 UTC, mywnajsldkf commented on 03 - CSS Variables/START.js
> + const picSize = this.dataset.sizing || '';
오 그렇군요! 좀 더 고민해서 수정하겠습니다.

2019-03-19 07:40 UTC, merged