[Judy] step2 구현완료
JNU-econovation/javascript-study-30days pull request #9
Opened 2019-03-07 11:24 UTC by mywnajsldkf

구현했습니다

2019-03-07 11:34 UTC, corykim0829 requested changes
js모듈로 분리하시고 조금 더 코드를 줄일 수 있으면 줄여보세요! 노트북이 없는데도 열심히 잘하셨습니다. Judy님 최고

2019-03-07 11:34 UTC, corykim0829 commented on 02 - JS and CSS Clock/index-START.html
>    <script>
js 파일 모듈로 분리해주세요!

2019-03-11 07:57 UTC, GiPyoo approved these changes
잘 구현 하셨습니다.

2019-03-11 07:59 UTC, GiPyoo reviewed
다만 파일 정리를 조금 더 하실 필요가 있을 것 같습니다. 사용하지 않는 태그라던지 빈 공백의 규칙성이라던지 띄어쓰기라던지
만약 vscode를 쓰신다면 간단히 단축키로 정리가 가능합니다.

2019-03-11 12:18 UTC, closed without merging